In [27]:
import pandas as pd
import numpy as np

In [69]:
import matplotlib.pyplot as plt 
import seaborn as sn
import plotly_express as px  

In [70]:
data = pd.DataFrame({'a': ['as', 'asd', 'asdf', 'asdfg'], 'b': [2, 4, 5, 6], 'c': [3, 6, 8, 10]})
data

a  b   c
0     as  2   3
1    asd  4   6
2   asdf  5   8
3  asdfg  6  10

In [71]:
user_dynamics = [-5, 2, 4, 8, 12, -7, 5] 
# Создаём цикл по индексам и элементам списка 
# i — индекс текущего элемента, dynamic — текущее значение из списка
for i, dynamic in enumerate(user_dynamics):
    # Выводим номер дня и динамику на этот день 
    print("Day {} : {}".format(i+1, dynamic)) 

Day 1 : -5
Day 2 : 2
Day 3 : 4
Day 4 : 8
Day 5 : 12
Day 6 : -7
Day 7 : 5


In [72]:
TN =6
FP = 9
TN = 14




(6+14)/(6+14+9+6)

0.5714285714285714

In [73]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
t[5]
len(t)

28

12

In [74]:
temp = min(t)
res = [i for i, j in enumerate(t) if j==temp]
res

[0]

In [75]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values[5,1]

44

In [76]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

Inc=np.array([Husband_Income,Wife_Income,Mother_In_Law_Income]).T
Inc[0,0], Inc[1,1], Inc[2,2]

(100, 200, 100)

In [77]:
Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])


Cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
Cons[0,0], Cons[1,1], Cons[2,2]

(50, 80, 140)

In [78]:
tax = Inc*0.87

In [79]:
P = tax-Cons
P[2, :]

array([ 61.8, -26.9, -53. ])

In [69]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")
A
B
A*B

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [93]:
c = np.array([[1, -5, 2], [2, 2, 2], [0, 3,1], [3,2,1]])
d = np.array([[3, 1, 0], [-1, 0, 2], [3,2,1]])
c
d
c@d
c*d

array([[ 1, -5,  2],
       [ 2,  2,  2],
       [ 0,  3,  1],
       [ 3,  2,  1]])

array([[ 3,  1,  0],
       [-1,  0,  2],
       [ 3,  2,  1]])

array([[14,  5, -8],
       [10,  6,  6],
       [ 0,  2,  7],
       [10,  5,  5]])

ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

In [89]:
4516-1590

2926

In [62]:
A*B

array([ 3, -5,  0, -2,  0,  6])

2

3

In [ ]:
ones = np.ones(5)
salon= ones - com
np.dot(dot,salon)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [102]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы с DataFrame 
from sklearn import datasets # для импорта данных
import seaborn as sns # для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

# загружаем датасет
boston = datasets.load_boston()
boston_data = pd.DataFrame(
    data=boston.data, #данные
    columns=boston.feature_names #наименования столбцов
)
boston_data['PRICE'] = boston.target
boston_data.head()

c:\Users\d3en\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the C

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [4]:
# составляем матрицу А и вектор целевой переменной
CRIM = boston_data['CRIM']
RM = boston_data['RM']
A = np.column_stack((np.ones(506), CRIM, RM))
y = boston_data[['PRICE']]
print(A)

[[1.0000e+00 6.3200e-03 6.5750e+00]
 [1.0000e+00 2.7310e-02 6.4210e+00]
 [1.0000e+00 2.7290e-02 7.1850e+00]
 ...
 [1.0000e+00 6.0760e-02 6.9760e+00]
 [1.0000e+00 1.0959e-01 6.7940e+00]
 [1.0000e+00 4.7410e-02 6.0300e+00]]


In [5]:
A.shape

(506, 3)

In [6]:
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat.values)

[[-29.24471945]
 [ -0.26491325]
 [  8.39106825]]


In [16]:
# добавились новые данные:
CRIM_new = 0.2
RM_new = 6
# делаем прогноз типичной стоимости дома
PRICE_new = w_hat.iloc[0]+w_hat.iloc[1]*CRIM_new+w_hat.iloc[2]*RM_new
print(PRICE_new.values)
## [37.85733519]

[21.04870738]


Для удобства дальнейшего использования оформим характеристики нового наблюдения в виде матрицы размером 1,3

In [17]:
# короткий способ сделать прогноз
new=np.array([[1,CRIM_new,RM_new]])
print('prediction:', (new@w_hat).values)
## prediction: [[37.85733519]]

prediction: [[21.04870738]]


In [18]:
from sklearn.linear_model import LinearRegression
# создаём модель линейной регрессии
model = LinearRegression(fit_intercept=False)
# вычисляем коэффициенты регрессии
model.fit(A, y)
print('w_hat:', model.coef_)
new_prediction = model.predict(new)
print('prediction:', new_prediction)
## w_hat: [[-29.24471945  -0.26491325   8.39106825]]
## prediction: [[37.85733519]]

LinearRegression(fit_intercept=False)

w_hat: [[-29.24471945  -0.26491325   8.39106825]]
prediction: [[21.04870738]]


In [94]:
v=np.array([[1,2], [3,7]])
w=np.array([4,4])
v
c = np.linalg.inv(v)
c@v

array([[1, 2],
       [3, 7]])

array([[ 1.00000000e+00, -1.77635684e-15],
       [ 0.00000000e+00,  1.00000000e+00]])

In [9]:
# создадим вырожденную матрицу А
A = np.array([[1,1,1,1],[1,3,-2,9],[1,9,4,81]]
).T
y = np.array([3,7,-5,21]).T

A
y
# вычислим OLS-оценку для коэффициентов
w_hat=np.linalg.inv(A.T@A)@A.T@y
print(np.round(w_hat, 1)) 
## LinAlgError: Singular matrix

array([[ 1,  1,  1],
       [ 1,  3,  9],
       [ 1, -2,  4],
       [ 1,  9, 81]])

array([ 3,  7, -5, 21])

[ 0.1  2.5 -0. ]


In [99]:
# создаём модель линейной регрессии
model = LinearRegression(fit_intercept=False)
# вычисляем коэффициенты регрессии
model.fit(A, y)
print('w_hat:', model.coef_)
## w_hat: [ 6.   -1.25  1.25]

LinearRegression(fit_intercept=False)

w_hat: [ 6.   -1.25  1.25]


In [100]:
np.linalg.lstsq(A, y, rcond=None)

(array([ 6.  , -1.25,  1.25]),
 array([], dtype=float64),
 2,
 array([4.86435029, 0.58146041, 0.        ]))

In [101]:
A = np.array([
    [1, 1, 1, 1],
    [1, 1, 0, 2],
    [-1, 1, 0, 0],
    [0, 2, 0, 2]
]).T
A
np.linalg.matrix_rank(A.T@A)

array([[ 1,  1, -1,  0],
       [ 1,  1,  1,  2],
       [ 1,  0,  0,  0],
       [ 1,  2,  0,  2]])

3

In [103]:
A = boston_data[['CHAS', 'LSTAT', 'CRIM','RM']]
y = boston_data[['PRICE']]
# стандартизируем векторы в столбцах матрицы A
A_cent = A - A.mean()
A_st = A_cent/np.linalg.norm(A_cent, axis=0)
A_st.describe().round(2)

CHAS   LSTAT    CRIM      RM
count  506.00  506.00  506.00  506.00
mean    -0.00   -0.00   -0.00   -0.00
std      0.04    0.04    0.04    0.04
min     -0.01   -0.07   -0.02   -0.17
25%     -0.01   -0.04   -0.02   -0.03
50%     -0.01   -0.01   -0.02   -0.00
75%     -0.01    0.03    0.00    0.02
max      0.16    0.16    0.44    0.16

In [111]:
y = np.array([12,8])
y_cent = y - y.mean()
y_st = y_cent/np.linalg.norm(y_cent)
y_st

array([ 0.70710678, -0.70710678])

In [137]:
x_1 = np.array([5.1,1.8,2.1,10.3,12.1,12.6]).T
x_2 = np.array([10.2,3.7,4.1,20.5,24.2,24.1]).T
x_3 = np.array([2.5,0.9,1.1,5.1,6.1,6.3])
X = np.corrcoef([x_1, x_2, x_3])

In [138]:
X

array([[1.        , 0.99925473, 0.99983661],
       [0.99925473, 1.        , 0.99906626],
       [0.99983661, 0.99906626, 1.        ]])

In [131]:
X

array([[ 5.1,  1.8,  2.1, 10.3, 12.1, 12.6],
       [10.2,  3.7,  4.1, 20.5, 24.2, 24.1],
       [ 2.5,  0.9,  1.1,  5.1,  6.1,  6.3]])

In [154]:
quest = np.linalg.det(X)
np.linalg.matrix_rank(X)
print(round(quest, 7))
print('asasas{:.7f}'.format(quest))

3

5e-07
asasas0.0000005


In [10]:
from sklearn.linear_model import Ridge

# матрица наблюдений (включая столбец единиц)
A = np.array([[1,1,1,1,1,],[1, 0, -3, 2, 4],
    [2, 0, -6, 4, 8]
]).T
# вектор целевого признака
y = np.array([4, 3, -4, 2, 7])
# получаем оценку коэффициентов регрессии по МНК с регуляризацией Тихонова
ridge = Ridge(alpha=5, fit_intercept=False)
ridge.fit(A, y)
print(ridge.coef_) 
print(ridge.intercept_)
## [0.6122449  0.29387755 0.5877551 ]

Ridge(alpha=5, fit_intercept=False)

[0.6122449  0.29387755 0.5877551 ]
0.0


In [37]:
w0 = np.ones([5])
x1 = np.array([5,9,4,3,5])
x2 = np.array([15,18,18,19,19])
x3 = np.array([7,6,7,7,7,])
y = np.array([24,22,35,33,36])

A = np.array([w0,x1,x2,x3]).T

E = np.eye(4)
alpha = 1

w_hat_ridge = np.linalg.inv(A.T@A+alpha*E)@A.T@y

In [45]:
from sklearn.linear_model import ElasticNet
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate

In [46]:
X = boston_data[['LSTAT', 'PTRATIO', 'RM','CRIM']]
y = boston_data[['PRICE']]
# инициализируем стандартизатор StandardScaler
scaler = StandardScaler()
# подгоняем параметры стандартизатора (вычисляем среднее и СКО)
X = scaler.fit_transform(X)
# добавляем полиномиальные признаки
poly = PolynomialFeatures(degree=3, include_bias=False)
X = poly.fit_transform(X)
# создаём модель линейной регрессии c L1- и L2-регуляризациями
lasso = ElasticNet(alpha=0.1, l1_ratio=0.5, max_iter=10000)
# оцениваем качество модели на кросс-валидации
cv_results = cross_validate(lasso, X, y, scoring='neg_mean_absolute_percentage_error', cv=5, return_train_score=True)
print('MAPE на тренировочных фолдах: {:.2f} %'.format(-cv_results['train_score'].mean()* 100))
print('MAPE на валидационных фолдах: {:.2f} %'.format(-cv_results['test_score'].mean() * 100)) 

MAPE на тренировочных фолдах: 12.65 %
MAPE на валидационных фолдах: 15.70 %


In [47]:
print('MAPE на тренировочных фолдах: {:.2f} %'.format(cv_results['train_score'].mean()* 100))
print('MAPE на валидационных фолдах: {:.2f} %'.format(cv_results['test_score'].mean() * 100)) 

MAPE на тренировочных фолдах: -12.65 %
MAPE на валидационных фолдах: -15.70 %
